"""Alembic script template."""

from alembic import op
import sqlalchemy as sa
revision = '5d1200ebf26e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('pdf_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_studied', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pdf_hash')
    )
    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('front', sa.String(), nullable=False),
    sa.Column('back', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('deck_id', sa.String(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cards_deck_due', 'cards', ['deck_id', 'due_date'], unique=False)
    op.create_index('ix_cards_deck_id', 'cards', ['deck_id'], unique=False)
    op.create_index('ix_cards_due_date', 'cards', ['due_date'], unique=False)
    op.create_table('review_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_logs_card_id', 'review_logs', ['card_id'], unique=False)
    op.create_index('ix_review_logs_reviewed_at', 'review_logs', ['reviewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_logs_reviewed_at', table_name='review_logs')
    op.drop_index('ix_review_logs_card_id', table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index('ix_cards_due_date', table_name='cards')
    op.drop_index('ix_cards_deck_id', table_name='cards')
    op.drop_index('ix_cards_deck_due', table_name='cards')
    op.drop_table('cards')
    op.drop_table('decks')
    # ### end Alembic commands ###
